sudo: required
language: c
services:
    - docker

env:
    matrix:
      - DOCKIMG=unidata/nctests:serial

before_install:
    - docker pull $DOCKIMG > /dev/null

script:
  - docker run --rm -it -e RUNF=OFF -e RUNCXX=OFF -e RUNP=OFF -e RUNNCO=OFF -e USECMAKE=TRUE -e USE_VALGRIND=TRUE -e CTEST_OUTPUT_ON_FAILURE=1 -v $(pwd):/netcdf-c $DOCKIMG
